// ===== 每日宇宙提示卡数据库 =====

export interface DailyCard {
  id: number;
  title: string;       // 卡片标题
  message: string;     // 主文案（直击心灵）
  subMessage: string;  // 副文案（补充与延伸）
  emoji: string;       // 主图标
  bgFrom: string;      // 渐变起始色
  bgTo: string;        // 渐变结束色
  accentColor: string; // 强调色
  category: string;    // 分类
}

export const DAILY_CARDS: DailyCard[] = [
  {
    id: 1,
    title: "宇宙提示",
    message: "今天不要急着做决定，让子弹飞一会儿。",
    subMessage: "有些事情需要时间发酵，不是拖延，而是尊重过程。",
    emoji: "🌌",
    bgFrom: "#0a0518",
    bgTo: "#1a0a35",
    accentColor: "#9B59B6",
    category: "智慧",
  },
  {
    id: 2,
    title: "今日能量",
    message: "你已经比昨天的自己进步了，哪怕只是一毫米。",
    subMessage: "成长不总是轰轰烈烈的，积土成山，每一步都算数。",
    emoji: "✨",
    bgFrom: "#0a1a2e",
    bgTo: "#0a2a4e",
    accentColor: "#3498DB",
    category: "成长",
  },
  {
    id: 3,
    title: "星际密语",
    message: "那个让你辗转反侧的人，可能已经把你忘了。放下吧。",
    subMessage: "不是所有的故事都需要一个完美的结局，有些人出现是为了教你成长。",
    emoji: "💫",
    bgFrom: "#180a2e",
    bgTo: "#300a50",
    accentColor: "#E91E8C",
    category: "情感",
  },
  {
    id: 4,
    title: "宇宙礼物",
    message: "今天会有一个小惊喜等着你，留意生活里的细节。",
    subMessage: "宇宙总是在恰当的时机送来惊喜，而那些人习惯性地错过了。",
    emoji: "🎁",
    bgFrom: "#1a1000",
    bgTo: "#352000",
    accentColor: "#FFB300",
    category: "好运",
  },
  {
    id: 5,
    title: "内在声音",
    message: "你的直觉一直都是对的，只是你不敢相信。",
    subMessage: "身体的感知比大脑的分析更诚实，学会聆听内心那个轻声细语。",
    emoji: "🌙",
    bgFrom: "#0d0a1a",
    bgTo: "#1a152e",
    accentColor: "#7C3AED",
    category: "直觉",
  },
  {
    id: 6,
    title: "能量提醒",
    message: "今天适合休息，不必证明什么，存在本身就有价值。",
    subMessage: "放下\"应该\"的重量，你不需要每天都成就非凡。",
    emoji: "🌿",
    bgFrom: "#0a1a0a",
    bgTo: "#0a2a15",
    accentColor: "#27AE60",
    category: "疗愈",
  },
  {
    id: 7,
    title: "宇宙提示",
    message: "那件你一直在拖延的事，今天就开始吧，开始了就成功了一半。",
    subMessage: "完美的时机永远不会来，唯有行动才能改变现状。",
    emoji: "⚡",
    bgFrom: "#1a0e00",
    bgTo: "#3a1500",
    accentColor: "#FF6B35",
    category: "行动",
  },
  {
    id: 8,
    title: "星光指引",
    message: "你值得被温柔对待，首先是来自你自己。",
    subMessage: "自我批判和自我苛责是最深的内耗，今天对自己好一点。",
    emoji: "💎",
    bgFrom: "#1a0a18",
    bgTo: "#2e0a2a",
    accentColor: "#E91E8C",
    category: "自爱",
  },
  {
    id: 9,
    title: "今日启示",
    message: "有些人的离开是命运在帮你腾出空间，迎接更好的。",
    subMessage: "告别有时候是祝福，让去的人去，让来的人来。",
    emoji: "🌸",
    bgFrom: "#1a0808",
    bgTo: "#2e1010",
    accentColor: "#E74C3C",
    category: "放下",
  },
  {
    id: 10,
    title: "宇宙信号",
    message: "你的焦虑是因为你把\"现在\"活在了\"未来\"里，回来。",
    subMessage: "深呼吸，此刻你是安全的，你所担心的大多数事情不会发生。",
    emoji: "🧘",
    bgFrom: "#0a0d1a",
    bgTo: "#0a1028",
    accentColor: "#4A9ECA",
    category: "正念",
  },
  {
    id: 11,
    title: "能量共振",
    message: "你的善良是你的超能力，不要因为被误解就失去它。",
    subMessage: "世界需要更多温柔的人，而你就是其中之一。",
    emoji: "💝",
    bgFrom: "#180a10",
    bgTo: "#2a0a1a",
    accentColor: "#E91E8C",
    category: "善良",
  },
  {
    id: 12,
    title: "星际传言",
    message: "今天不要跟不值得的人消耗能量，保护好你的频率。",
    subMessage: "你的注意力是稀缺资源，不要浪费在让你变差的人事物上。",
    emoji: "🛡️",
    bgFrom: "#0d0d0d",
    bgTo: "#1a1a2a",
    accentColor: "#7F8C8D",
    category: "边界",
  },
  {
    id: 13,
    title: "内心灯塔",
    message: "哭了也没关系，眼泪是情绪的出口，不是软弱的证明。",
    subMessage: "允许自己脆弱，才能真正强大；感受痛苦，才能真正愈合。",
    emoji: "🌊",
    bgFrom: "#0a1218",
    bgTo: "#0a1e2e",
    accentColor: "#2E86C1",
    category: "疗愈",
  },
  {
    id: 14,
    title: "宇宙礼物",
    message: "那个你觉得\"还不够好\"的自己，已经让很多人羡慕了。",
    subMessage: "停止和别人比较，开始欣赏自己拥有的一切，你比你以为的更丰盛。",
    emoji: "🌟",
    bgFrom: "#181000",
    bgTo: "#2e2000",
    accentColor: "#F0A500",
    category: "感恩",
  },
  {
    id: 15,
    title: "今日能量",
    message: "喜欢的人迟迟不回复？先去做让自己开心的事。",
    subMessage: "你的快乐不应该被别人的回复时间决定，爱自己才是最重要的。",
    emoji: "📱",
    bgFrom: "#180a18",
    bgTo: "#2a0a2a",
    accentColor: "#AF7AC5",
    category: "情感",
  },
  {
    id: 16,
    title: "宇宙提示",
    message: "今天的你很美，就算你自己没注意到。",
    subMessage: "美是一种光，它从内心发出，照亮了你周围的每一个人。",
    emoji: "🌺",
    bgFrom: "#1a0a10",
    bgTo: "#2a0a18",
    accentColor: "#E91E8C",
    category: "自爱",
  },
  {
    id: 17,
    title: "星际密语",
    message: "钱是会来的，先把自己的状态调整好，财运跟着能量走。",
    subMessage: "匮乏感本身会阻塞丰盛，先感恩你已经拥有的，更多的才会来。",
    emoji: "💰",
    bgFrom: "#181200",
    bgTo: "#2a1e00",
    accentColor: "#C9A84C",
    category: "财运",
  },
  {
    id: 18,
    title: "光明预言",
    message: "你以为的终点，其实是转折点。最坏的时候往往也是转机。",
    subMessage: "黎明之前是最黑暗的，但黑暗不是终点，它是光的前奏。",
    emoji: "🌅",
    bgFrom: "#1a0800",
    bgTo: "#3a1500",
    accentColor: "#E74C3C",
    category: "希望",
  },
  {
    id: 19,
    title: "内在声音",
    message: "那个选择，你其实已经做决定了，只是需要勇气承认。",
    subMessage: "你的心已经知道答案，只需要给自己允许的力量。",
    emoji: "🗝️",
    bgFrom: "#0d0d1a",
    bgTo: "#1a1a2e",
    accentColor: "#5499C7",
    category: "决策",
  },
  {
    id: 20,
    title: "宇宙信号",
    message: "今天遇到的那个有趣的人，或许不只是偶然。",
    subMessage: "宇宙在精心安排每一次相遇，带着好奇心去打开那扇门。",
    emoji: "🤝",
    bgFrom: "#0a180a",
    bgTo: "#102e15",
    accentColor: "#58D68D",
    category: "缘分",
  },
  {
    id: 21,
    title: "今日启示",
    message: "有时候\"不知道怎么办\"本身就是答案：先别办。",
    subMessage: "不行动也是一种选择，给自己时间等待清晰，不必急于解决所有问题。",
    emoji: "☁️",
    bgFrom: "#0d0d18",
    bgTo: "#181820",
    accentColor: "#85929E",
    category: "智慧",
  },
  {
    id: 22,
    title: "能量充电",
    message: "你需要的不是更多努力，而是更好的休息。",
    subMessage: "疲惫的时候，允许自己停下来。充满电的你才能走得更远。",
    emoji: "🌙",
    bgFrom: "#08080f",
    bgTo: "#10101e",
    accentColor: "#6C7BFF",
    category: "休息",
  },
  {
    id: 23,
    title: "宇宙提示",
    message: "那件担心会失去的事，也许是宇宙在为更好的东西腾位置。",
    subMessage: "\"失去\"往往是\"获得\"的序言，放开紧握的手，才能接住更好的礼物。",
    emoji: "🦋",
    bgFrom: "#0a0818",
    bgTo: "#150e28",
    accentColor: "#8E44AD",
    category: "放下",
  },
  {
    id: 24,
    title: "星光传信",
    message: "你说的\"等以后\"，从今天开始就是现在。",
    subMessage: "\"以后\"是个谎言，唯有此刻才是你真正能掌握的时间。",
    emoji: "⏰",
    bgFrom: "#1a0e00",
    bgTo: "#2a1800",
    accentColor: "#D35400",
    category: "当下",
  },
  {
    id: 25,
    title: "今日能量",
    message: "今天是适合表白的日子，不管是对喜欢的人，还是对自己。",
    subMessage: "爱是需要说出口的，不要让\"以为对方知道\"成为遗憾的借口。",
    emoji: "💌",
    bgFrom: "#1a0808",
    bgTo: "#2e1010",
    accentColor: "#E74C3C",
    category: "情感",
  },
  {
    id: 26,
    title: "宇宙密码",
    message: "注意今天出现在你生命里的数字，它可能是宇宙的暗号。",
    subMessage: "有意识地观察，有时候重复出现的数字、颜色或名字都是信号。",
    emoji: "🔢",
    bgFrom: "#060818",
    bgTo: "#0a0e28",
    accentColor: "#4A9ECA",
    category: "神秘",
  },
  {
    id: 27,
    title: "内在光",
    message: "你不需要任何人的许可，就可以成为你想成为的人。",
    subMessage: "你的价值不由他人评定，你的人生不需要任何人的认可才能开始。",
    emoji: "🔥",
    bgFrom: "#1a0800",
    bgTo: "#2e1200",
    accentColor: "#E67E22",
    category: "自主",
  },
  {
    id: 28,
    title: "宇宙提示",
    message: "今天适合一个人做一件取悦自己的小事。",
    subMessage: "给自己买一杯喜欢的饮料，看一部积压已久的电影，做一件平时'不值得'做的事。",
    emoji: "🎪",
    bgFrom: "#0e0a1a",
    bgTo: "#1a1028",
    accentColor: "#AF7AC5",
    category: "自爱",
  },
  {
    id: 29,
    title: "星际预言",
    message: "你以为最差的选择，往往会引领你到意想不到的美好。",
    subMessage: "生命不是非此即彼，每一条路都有它的风景，走错了也是经历。",
    emoji: "🗺️",
    bgFrom: "#0a100a",
    bgTo: "#0a1a0e",
    accentColor: "#27AE60",
    category: "勇气",
  },
  {
    id: 30,
    title: "宇宙心跳",
    message: "今天，只需要深呼吸，感受活着的奇迹。",
    subMessage: "你存在着，你呼吸着，你感受着——这已经是奇迹了。",
    emoji: "💓",
    bgFrom: "#0a0812",
    bgTo: "#14101e",
    accentColor: "#C084FC",
    category: "正念",
  },
];

// 根据日期获取当日卡片
export function getDailyCard(): DailyCard {
  const today = new Date();
  const dayOfYear = Math.floor(
    (today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000
  );
  const index = dayOfYear % DAILY_CARDS.length;
  return DAILY_CARDS[index]!;
}

// 获取今日日期字符串
export function getTodayString(): string {
  const now = new Date();
  const options: Intl.DateTimeFormatOptions = {
    year: "numeric",
    month: "long",
    day: "numeric",
    weekday: "long",
  };
  return now.toLocaleDateString("zh-CN", options);
}
