// ── AI 解忧馆：新手步骤 / SEO 内容 / FAQ（三语）──────────────
// page.tsx 与 layout.tsx（FAQPage JSON-LD）共用，保证数据同源。
export type AiMysticLang = "zh" | "en" | "tw";

export interface AiMysticSeo {
  howToTitle: string;
  howToSteps: string[];
  seoSections: { heading: string; body: string }[];
  faqTitle: string;
  faq: { q: string; a: string }[];
}

export const AI_MYSTIC_SEO: Record<AiMysticLang, AiMysticSeo> = {
  zh: {
    howToTitle: "怎么玩？",
    howToSteps: [
      "点击一个快速问题，或在输入框里写下你的烦恼",
      "按 Enter 发送（Shift+Enter 换行），小云会为你抽一张塔罗牌",
      "阅读结合牌意的专属回应，感受被倾听与理解",
      "继续追问可以多轮深入，聊过的牌和话题都会被记住",
    ],
    seoSections: [
      {
        heading: "什么是 AI 解忧馆？",
        body: "AI 解忧馆是一个随时在线的 AI 塔罗倾诉空间。你可以像和朋友聊天一样，把感情、职场、财富或生活上的烦恼说出来，AI 塔罗师「小云」会结合塔罗牌意给出温暖而具体的回应。无需注册，打开就能聊。",
      },
      {
        heading: "AI 塔罗聊天是如何工作的？",
        body: "每次你发送消息，小云都会为你抽取一张塔罗牌，并综合你当前的提问、聊过的话题与此前出现的牌，生成贴合语境的解读。多轮对话中它会记住你们的上下文，越聊越贴近你的真实处境。",
      },
      {
        heading: "倾诉小贴士",
        body: "描述越具体，回应越贴心：试着说清发生了什么、你的感受是什么。把这里当作情绪树洞与自我探索的镜子，而不是决策的唯一依据——重要的决定仍要听从理性与现实。",
      },
    ],
    faqTitle: "常见问题",
    faq: [
      {
        q: "AI 解忧馆是免费的吗？",
        a: "是的，完全免费，无需注册登录。打开页面即可开始与 AI 塔罗师对话，想聊多久都可以。",
      },
      {
        q: "我的聊天内容会被保存吗？",
        a: "对话仅存在于当前页面会话中，刷新页面后即重新开始。你的倾诉内容不会被用于其他用途。",
      },
      {
        q: "AI 的回答是真正的占卜吗？",
        a: "小云的回答由 AI 结合塔罗牌意生成，适合情绪疏导与自我探索参考。请理性看待，不要把它当作重大决策的唯一依据。",
      },
      {
        q: "可以聊哪些话题？",
        a: "感情、工作、财富、压力与焦虑等都可以聊。你也可以直接提到某张塔罗牌的名字，小云会为你解读它的寓意。",
      },
    ],
  },
  tw: {
    howToTitle: "怎麼玩？",
    howToSteps: [
      "點擊一個快速問題，或在輸入框裡寫下你的煩惱",
      "按 Enter 送出（Shift+Enter 換行），小雲會為你抽一張塔羅牌",
      "閱讀結合牌意的專屬回應，感受被傾聽與理解",
      "繼續追問可以多輪深入，聊過的牌和話題都會被記住",
    ],
    seoSections: [
      {
        heading: "什麼是 AI 解憂館？",
        body: "AI 解憂館是一個隨時在線的 AI 塔羅傾訴空間。你可以像和朋友聊天一樣，把感情、職場、財富或生活上的煩惱說出來，AI 塔羅師「小雲」會結合塔羅牌意給出溫暖而具體的回應。無需註冊，打開就能聊。",
      },
      {
        heading: "AI 塔羅聊天是如何運作的？",
        body: "每次你送出訊息，小雲都會為你抽取一張塔羅牌，並綜合你當前的提問、聊過的話題與此前出現的牌，生成貼合語境的解讀。多輪對話中它會記住你們的上下文，越聊越貼近你的真實處境。",
      },
      {
        heading: "傾訴小貼士",
        body: "描述越具體，回應越貼心：試著說清發生了什麼、你的感受是什麼。把這裡當作情緒樹洞與自我探索的鏡子，而不是決策的唯一依據——重要的決定仍要聽從理性與現實。",
      },
    ],
    faqTitle: "常見問題",
    faq: [
      {
        q: "AI 解憂館是免費的嗎？",
        a: "是的，完全免費，無需註冊登入。打開頁面即可開始與 AI 塔羅師對話，想聊多久都可以。",
      },
      {
        q: "我的聊天內容會被保存嗎？",
        a: "對話僅存在於當前頁面會話中，重新整理頁面後即重新開始。你的傾訴內容不會被用於其他用途。",
      },
      {
        q: "AI 的回答是真正的占卜嗎？",
        a: "小雲的回答由 AI 結合塔羅牌意生成，適合情緒疏導與自我探索參考。請理性看待，不要把它當作重大決策的唯一依據。",
      },
      {
        q: "可以聊哪些話題？",
        a: "感情、工作、財富、壓力與焦慮等都可以聊。你也可以直接提到某張塔羅牌的名字，小雲會為你解讀它的寓意。",
      },
    ],
  },
  en: {
    howToTitle: "How it works",
    howToSteps: [
      "Tap a quick question, or type what's troubling you in the input box",
      "Press Enter to send (Shift+Enter for a new line) — Cloudy draws a tarot card for you",
      "Read the response woven from the card's meaning, and feel heard",
      "Keep asking to go deeper over multiple rounds — cards and topics are remembered",
    ],
    seoSections: [
      {
        heading: "What is the AI Oracle Lounge?",
        body: "The AI Oracle Lounge is an always-on space to confide in an AI tarot reader. Talk as you would to a friend about love, career, money, or life's worries, and Cloudy, the AI tarot companion, responds with warmth and specifics drawn from the tarot. No sign-up — just open the page and start talking.",
      },
      {
        heading: "How does AI tarot chat work?",
        body: "Each time you send a message, Cloudy draws a tarot card for you and crafts a reply that combines your current question, the topics you've discussed, and the cards that appeared earlier. Across multiple rounds it keeps your context, so the conversation moves ever closer to your real situation.",
      },
      {
        heading: "Tips for a better reading",
        body: "The more specific you are, the more personal the response: try to say what happened and how it made you feel. Treat this space as an emotional outlet and a mirror for self-exploration rather than the sole basis for decisions — big choices still belong to reason and reality.",
      },
    ],
    faqTitle: "FAQ",
    faq: [
      {
        q: "Is the AI Oracle Lounge free?",
        a: "Yes — completely free, with no sign-up or login. Open the page and start chatting with the AI tarot reader for as long as you like.",
      },
      {
        q: "Is my chat history saved?",
        a: "The conversation lives only in your current page session and starts fresh when you reload. What you share is not used for any other purpose.",
      },
      {
        q: "Are the AI's answers real divination?",
        a: "Cloudy's replies are generated by AI from tarot card meanings, and are best used for emotional support and self-reflection. Take them lightly — don't make them the sole basis for major decisions.",
      },
      {
        q: "What topics can I talk about?",
        a: "Love, work, money, stress and anxiety are all welcome. You can also mention a tarot card by name, and Cloudy will explain what it means.",
      },
    ],
  },
};
