// 塔罗牌完整数据（78张韦特塔罗牌）
// 图片来自 public/images/cards/ 目录

export interface TarotCard {
  id: string;
  name: string;
  nameCn: string;
  type: "major" | "minor";
  suit?: string;
  value: string;
  imageFile: string;
  meaningUp: string;
  meaningRev: string;
  keywords: string[];
}

export const TAROT_CARDS: TarotCard[] = [
  // ===== 大阿尔卡纳 (Major Arcana) =====
  {
    id: "ar00",
    name: "The Fool",
    nameCn: "愚者",
    type: "major",
    value: "0",
    imageFile: "MW_The_Fool.jpg",
    meaningUp: "新的开始、自由奔放、纯真无邪、冒险精神",
    meaningRev: "鲁莽冒进、无视风险、缺乏计划、逃避责任",
    keywords: ["新开始", "自由", "冒险", "纯真"],
  },
  {
    id: "ar01",
    name: "The Magician",
    nameCn: "魔术师",
    type: "major",
    value: "1",
    imageFile: "MW_The_Magician.jpg",
    meaningUp: "意志力、技巧、自信、创造力、行动力",
    meaningRev: "欺骗、操纵、能力不足、潜能未发挥",
    keywords: ["意志", "技巧", "创造", "行动"],
  },
  {
    id: "ar02",
    name: "The High Priestess",
    nameCn: "女祭司",
    type: "major",
    value: "2",
    imageFile: "MW_The_High_Priestess.jpg",
    meaningUp: "直觉、神秘、内在智慧、潜意识、耐心",
    meaningRev: "隐藏的议题、表面知识、压抑直觉",
    keywords: ["直觉", "神秘", "智慧", "内省"],
  },
  {
    id: "ar03",
    name: "The Empress",
    nameCn: "女皇",
    type: "major",
    value: "3",
    imageFile: "MW_The_Empress.jpg",
    meaningUp: "丰盛、母性、创造力、自然、繁荣",
    meaningRev: "依赖、创造阻塞、过度溺爱、缺乏安全感",
    keywords: ["丰盛", "母性", "创造", "繁荣"],
  },
  {
    id: "ar04",
    name: "The Emperor",
    nameCn: "皇帝",
    type: "major",
    value: "4",
    imageFile: "MW_The_Emperor.jpg",
    meaningUp: "权威、稳定、结构、领导力、保护",
    meaningRev: "独裁、僵化、控制欲强、缺乏灵活性",
    keywords: ["权威", "稳定", "领导", "保护"],
  },
  {
    id: "ar05",
    name: "The Hierophant",
    nameCn: "教皇",
    type: "major",
    value: "5",
    imageFile: "MW_The_Hierophant.jpg",
    meaningUp: "传统、制度、精神指引、信仰、知识传承",
    meaningRev: "打破传统、反叛权威、个人信仰、改革",
    keywords: ["传统", "信仰", "指引", "制度"],
  },
  {
    id: "ar06",
    name: "The Lovers",
    nameCn: "恋人",
    type: "major",
    value: "6",
    imageFile: "MW_The_Lovers.jpg",
    meaningUp: "爱情、关系、和谐、价值观对齐、选择",
    meaningRev: "不和谐、价值观冲突、错误选择、关系危机",
    keywords: ["爱情", "和谐", "选择", "关系"],
  },
  {
    id: "ar07",
    name: "The Chariot",
    nameCn: "战车",
    type: "major",
    value: "7",
    imageFile: "MW_The_Chariot.jpg",
    meaningUp: "胜利、意志力、决心、控制、克服障碍",
    meaningRev: "失控、方向迷失、缺乏自律、挫败",
    keywords: ["胜利", "意志", "前进", "控制"],
  },
  {
    id: "ar08",
    name: "Strength",
    nameCn: "力量",
    type: "major",
    value: "8",
    imageFile: "MW_Strength.jpg",
    meaningUp: "内在力量、勇气、耐心、慈悲、自我控制",
    meaningRev: "软弱、自我怀疑、压抑情感、缺乏勇气",
    keywords: ["勇气", "耐心", "内在力量", "慈悲"],
  },
  {
    id: "ar09",
    name: "The Hermit",
    nameCn: "隐者",
    type: "major",
    value: "9",
    imageFile: "MW_The_Hermit.jpg",
    meaningUp: "独处、内省、寻求智慧、引导、沉思",
    meaningRev: "孤立、拒绝帮助、过度隐居、迷失方向",
    keywords: ["内省", "智慧", "独处", "沉思"],
  },
  {
    id: "ar10",
    name: "Wheel of Fortune",
    nameCn: "命运之轮",
    type: "major",
    value: "10",
    imageFile: "MW_Wheel_of_Fortune.jpg",
    meaningUp: "命运转机、好运、周期变化、机缘巧合",
    meaningRev: "坏运气、抵制变化、命运阻滞、业力",
    keywords: ["命运", "转机", "变化", "机缘"],
  },
  {
    id: "ar11",
    name: "Justice",
    nameCn: "正义",
    type: "major",
    value: "11",
    imageFile: "MW_Justice.jpg",
    meaningUp: "公平、真相、因果、法律、平衡",
    meaningRev: "不公正、逃避责任、失衡、腐败",
    keywords: ["公平", "真相", "因果", "平衡"],
  },
  {
    id: "ar12",
    name: "The Hanged Man",
    nameCn: "倒吊人",
    type: "major",
    value: "12",
    imageFile: "MW_The_Hangedman.jpg",
    meaningUp: "暂停、新视角、牺牲、等待、放手",
    meaningRev: "停滞、无谓牺牲、拖延、抵制改变",
    keywords: ["暂停", "视角", "牺牲", "等待"],
  },
  {
    id: "ar13",
    name: "Death",
    nameCn: "死神",
    type: "major",
    value: "13",
    imageFile: "MW_Death.jpg",
    meaningUp: "转变、终结与开始、蜕变、放下过去",
    meaningRev: "抵制改变、停滞不前、腐败、无法放手",
    keywords: ["转变", "终结", "蜕变", "新生"],
  },
  {
    id: "ar14",
    name: "Temperance",
    nameCn: "节制",
    type: "major",
    value: "14",
    imageFile: "MW_Temperance.jpg",
    meaningUp: "平衡、耐心、调和、适度、治愈",
    meaningRev: "不均衡、过度、缺乏耐心、冲突",
    keywords: ["平衡", "调和", "耐心", "治愈"],
  },
  {
    id: "ar15",
    name: "The Devil",
    nameCn: "恶魔",
    type: "major",
    value: "15",
    imageFile: "MW_The_Devil.jpg",
    meaningUp: "束缚、执念、物质主义、阴暗面、诱惑",
    meaningRev: "解脱束缚、释放、重获自由、正视阴暗面",
    keywords: ["束缚", "执念", "解脱", "阴影"],
  },
  {
    id: "ar16",
    name: "The Tower",
    nameCn: "塔",
    type: "major",
    value: "16",
    imageFile: "MW_The_Tower.jpg",
    meaningUp: "突然变化、崩塌、启示、打破旧结构",
    meaningRev: "逃避灾难、恐惧变化、延迟崩塌",
    keywords: ["变化", "崩塌", "启示", "重建"],
  },
  {
    id: "ar17",
    name: "The Star",
    nameCn: "星星",
    type: "major",
    value: "17",
    imageFile: "MW_The_Star.jpg",
    meaningUp: "希望、灵感、宁静、更新、信念",
    meaningRev: "绝望、失去信心、悲观、迷失方向",
    keywords: ["希望", "灵感", "宁静", "信念"],
  },
  {
    id: "ar18",
    name: "The Moon",
    nameCn: "月亮",
    type: "major",
    value: "18",
    imageFile: "MW_The_Moon.jpg",
    meaningUp: "幻觉、恐惧、潜意识、混乱、直觉",
    meaningRev: "揭示真相、释放恐惧、面对现实",
    keywords: ["幻觉", "潜意识", "直觉", "神秘"],
  },
  {
    id: "ar19",
    name: "The Sun",
    nameCn: "太阳",
    type: "major",
    value: "19",
    imageFile: "MW_The_Sun.jpg",
    meaningUp: "喜悦、成功、活力、积极、清晰",
    meaningRev: "悲观、延迟成功、能量不足、自我怀疑",
    keywords: ["喜悦", "成功", "活力", "光明"],
  },
  {
    id: "ar20",
    name: "Judgement",
    nameCn: "审判",
    type: "major",
    value: "20",
    imageFile: "MW_Judgement.jpg",
    meaningUp: "觉醒、更新、反思、内在呼召、宽恕",
    meaningRev: "自我怀疑、拒绝改变、逃避审判",
    keywords: ["觉醒", "更新", "反思", "宽恕"],
  },
  {
    id: "ar21",
    name: "The World",
    nameCn: "世界",
    type: "major",
    value: "21",
    imageFile: "MW_The_World.jpg",
    meaningUp: "完成、整合、成就、旅程结束、圆满",
    meaningRev: "未完成、阻滞、缺乏完结、遗憾",
    keywords: ["完成", "成就", "圆满", "整合"],
  },

  // ===== 小阿尔卡纳 - 权杖组 (Wands) =====
  {
    id: "wa01",
    name: "Ace of Wands",
    nameCn: "权杖王牌",
    type: "minor",
    suit: "wands",
    value: "1",
    imageFile: "MW_Ace_of_Wands.jpg",
    meaningUp: "新的创意、激情、灵感涌现、创业精神",
    meaningRev: "创意受阻、延迟启动、缺乏动力",
    keywords: ["激情", "创意", "启动", "灵感"],
  },
  {
    id: "wa02",
    name: "Two of Wands",
    nameCn: "权杖二",
    type: "minor",
    suit: "wands",
    value: "2",
    imageFile: "MW_Two_of_Wands.jpg",
    meaningUp: "规划未来、前瞻性、合作、进取",
    meaningRev: "缺乏计划、恐惧未知、犹豫不决",
    keywords: ["规划", "前瞻", "合作", "进取"],
  },
  {
    id: "wa03",
    name: "Three of Wands",
    nameCn: "权杖三",
    type: "minor",
    suit: "wands",
    value: "3",
    imageFile: "MW_Three_of_Wands.jpg",
    meaningUp: "扩展视野、等待结果、远大目标",
    meaningRev: "等待受挫、计划落空、目光短浅",
    keywords: ["扩展", "等待", "目标", "远见"],
  },
  {
    id: "wa04",
    name: "Four of Wands",
    nameCn: "权杖四",
    type: "minor",
    suit: "wands",
    value: "4",
    imageFile: "MW_Four_of_Wands.jpg",
    meaningUp: "庆祝、稳定、家庭和谐、里程碑",
    meaningRev: "家庭矛盾、庆祝推迟、不稳定感",
    keywords: ["庆祝", "稳定", "和谐", "家庭"],
  },
  {
    id: "wa05",
    name: "Five of Wands",
    nameCn: "权杖五",
    type: "minor",
    suit: "wands",
    value: "5",
    imageFile: "MW_Five_of_Wands.jpg",
    meaningUp: "竞争、冲突、意见分歧、挑战",
    meaningRev: "避免冲突、达成共识、内心矛盾解决",
    keywords: ["竞争", "冲突", "挑战", "意见"],
  },
  {
    id: "wa06",
    name: "Six of Wands",
    nameCn: "权杖六",
    type: "minor",
    suit: "wands",
    value: "6",
    imageFile: "MW_Six_of_Wands.jpg",
    meaningUp: "胜利、认可、成就、公众认可",
    meaningRev: "自我怀疑、缺乏认可、傲慢",
    keywords: ["胜利", "认可", "成就", "荣耀"],
  },
  {
    id: "wa07",
    name: "Seven of Wands",
    nameCn: "权杖七",
    type: "minor",
    suit: "wands",
    value: "7",
    imageFile: "MW_Seven_of_Wands.jpg",
    meaningUp: "坚持立场、挑战不断、勇于防守",
    meaningRev: "退缩、投降、被压倒感",
    keywords: ["坚持", "防守", "挑战", "立场"],
  },
  {
    id: "wa08",
    name: "Eight of Wands",
    nameCn: "权杖八",
    type: "minor",
    suit: "wands",
    value: "8",
    imageFile: "MW_Eight_of_Wands.png",
    meaningUp: "快速行动、消息传来、旅行、急速发展",
    meaningRev: "延迟、拖延、急于求成、沟通受阻",
    keywords: ["速度", "行动", "旅行", "消息"],
  },
  {
    id: "wa09",
    name: "Nine of Wands",
    nameCn: "权杖九",
    type: "minor",
    suit: "wands",
    value: "9",
    imageFile: "MW_Nine_of_Wands.jpg",
    meaningUp: "坚韧不拔、接近终点、警惕防守",
    meaningRev: "极度疲惫、偏执、放弃",
    keywords: ["坚韧", "防守", "疲惫", "警惕"],
  },
  {
    id: "wa10",
    name: "Ten of Wands",
    nameCn: "权杖十",
    type: "minor",
    suit: "wands",
    value: "10",
    imageFile: "MW_Ten_of_Wands.jpg",
    meaningUp: "过度负担、责任繁重、坚持完成",
    meaningRev: "卸下负担、学会委托、拒绝承担",
    keywords: ["负担", "责任", "坚持", "压力"],
  },
  {
    id: "wa11",
    name: "Page of Wands",
    nameCn: "权杖侍从",
    type: "minor",
    suit: "wands",
    value: "11",
    imageFile: "MW_Page_of_Wands.jpg",
    meaningUp: "热情探索、好奇心、勇于尝试、消息",
    meaningRev: "缺乏方向、轻率鲁莽、坏消息",
    keywords: ["探索", "热情", "好奇", "尝试"],
  },
  {
    id: "wa12",
    name: "Knight of Wands",
    nameCn: "权杖骑士",
    type: "minor",
    suit: "wands",
    value: "12",
    imageFile: "MW_Knight_of_Wands.jpg",
    meaningUp: "冒险精神、激情行动、充满活力、旅行",
    meaningRev: "冲动鲁莽、缺乏耐心、挫折",
    keywords: ["冒险", "激情", "活力", "行动"],
  },
  {
    id: "wa13",
    name: "Queen of Wands",
    nameCn: "权杖皇后",
    type: "minor",
    suit: "wands",
    value: "13",
    imageFile: "MW_Queen_of_Wands.jpg",
    meaningUp: "自信魅力、独立热情、创造力、领导",
    meaningRev: "妒忌、支配欲、不安全感",
    keywords: ["自信", "魅力", "独立", "创造"],
  },
  {
    id: "wa14",
    name: "King of Wands",
    nameCn: "权杖国王",
    type: "minor",
    suit: "wands",
    value: "14",
    imageFile: "MW_King_of_Wands.jpg",
    meaningUp: "有远见的领导者、企业家精神、魅力领袖",
    meaningRev: "独裁、急躁、期望过高",
    keywords: ["领导", "远见", "魅力", "企业"],
  },

  // ===== 小阿尔卡纳 - 圣杯组 (Cups) =====
  {
    id: "cu01",
    name: "Ace of Cups",
    nameCn: "圣杯王牌",
    type: "minor",
    suit: "cups",
    value: "1",
    imageFile: "MW_Ace_of_Cups.jpg",
    meaningUp: "新感情、情感开放、爱的开始、直觉涌现",
    meaningRev: "情感压抑、失落、情感受阻",
    keywords: ["新感情", "情感", "爱", "开放"],
  },
  {
    id: "cu02",
    name: "Two of Cups",
    nameCn: "圣杯二",
    type: "minor",
    suit: "cups",
    value: "2",
    imageFile: "MW_Two_of_Cups.jpg",
    meaningUp: "伙伴关系、相互吸引、情感连接、和谐",
    meaningRev: "关系破裂、不和谐、失去平衡",
    keywords: ["伙伴", "吸引", "连接", "和谐"],
  },
  {
    id: "cu03",
    name: "Three of Cups",
    nameCn: "圣杯三",
    type: "minor",
    suit: "cups",
    value: "3",
    imageFile: "MW_Three_of_Cups.jpg",
    meaningUp: "庆祝、友谊、欢乐、团聚、社交",
    meaningRev: "过度放纵、朋友背叛、孤立",
    keywords: ["庆祝", "友谊", "欢乐", "团聚"],
  },
  {
    id: "cu04",
    name: "Four of Cups",
    nameCn: "圣杯四",
    type: "minor",
    suit: "cups",
    value: "4",
    imageFile: "MW_Four_of_Cups.jpg",
    meaningUp: "冥想、内省、不满足、无聊、新机遇被忽视",
    meaningRev: "退缩、走出低谷、重新参与",
    keywords: ["内省", "冥想", "不满", "机遇"],
  },
  {
    id: "cu05",
    name: "Five of Cups",
    nameCn: "圣杯五",
    type: "minor",
    suit: "cups",
    value: "5",
    imageFile: "MW_Five_of_Cups.jpg",
    meaningUp: "失落、悲伤、后悔、失望、着眼于损失",
    meaningRev: "接受失去、向前看、原谅自己",
    keywords: ["失落", "悲伤", "后悔", "接受"],
  },
  {
    id: "cu06",
    name: "Six of Cups",
    nameCn: "圣杯六",
    type: "minor",
    suit: "cups",
    value: "6",
    imageFile: "MW_Six_of_Cups.jpg",
    meaningUp: "怀旧、童年记忆、无邪、旧日重逢",
    meaningRev: "活在过去、理想化过去、固执于童年",
    keywords: ["怀旧", "童年", "无邪", "记忆"],
  },
  {
    id: "cu07",
    name: "Seven of Cups",
    nameCn: "圣杯七",
    type: "minor",
    suit: "cups",
    value: "7",
    imageFile: "MW_Seven_of_Cups.jpg",
    meaningUp: "幻想、选择太多、白日梦、愿望",
    meaningRev: "清醒面对现实、做出选择、集中目标",
    keywords: ["幻想", "选择", "愿望", "梦想"],
  },
  {
    id: "cu08",
    name: "Eight of Cups",
    nameCn: "圣杯八",
    type: "minor",
    suit: "cups",
    value: "8",
    imageFile: "MW_Eight_of_Cups.jpg",
    meaningUp: "离开、寻找更深意义、放弃不满足的事物",
    meaningRev: "害怕离开、回避、留在不满的地方",
    keywords: ["离开", "寻找", "放弃", "意义"],
  },
  {
    id: "cu09",
    name: "Nine of Cups",
    nameCn: "圣杯九",
    type: "minor",
    suit: "cups",
    value: "9",
    imageFile: "MW_Nine_of_Cups.jpg",
    meaningUp: "满足感、愿望实现、感官享受、幸福",
    meaningRev: "不满足、物质主义、过度放纵",
    keywords: ["满足", "愿望", "幸福", "享受"],
  },
  {
    id: "cu10",
    name: "Ten of Cups",
    nameCn: "圣杯十",
    type: "minor",
    suit: "cups",
    value: "10",
    imageFile: "MW_Ten_of_Cups.jpg",
    meaningUp: "家庭幸福、情感满足、梦想成真、和谐",
    meaningRev: "家庭不和、理想破灭、价值观冲突",
    keywords: ["幸福", "家庭", "满足", "和谐"],
  },
  {
    id: "cu11",
    name: "Page of Cups",
    nameCn: "圣杯侍从",
    type: "minor",
    suit: "cups",
    value: "11",
    imageFile: "MW_Page_of_Cups.jpg",
    meaningUp: "创意、直觉、好消息、情感消息",
    meaningRev: "情感不成熟、坏消息、幻想脱离现实",
    keywords: ["创意", "直觉", "消息", "情感"],
  },
  {
    id: "cu12",
    name: "Knight of Cups",
    nameCn: "圣杯骑士",
    type: "minor",
    suit: "cups",
    value: "12",
    imageFile: "MW_Knight_of_Cups.jpg",
    meaningUp: "浪漫、魅力、追求理想、情感行动",
    meaningRev: "情绪化、嫉妒、不现实",
    keywords: ["浪漫", "魅力", "理想", "追求"],
  },
  {
    id: "cu13",
    name: "Queen of Cups",
    nameCn: "圣杯皇后",
    type: "minor",
    suit: "cups",
    value: "13",
    imageFile: "MW_Queen_of_Cups.jpg",
    meaningUp: "情感智慧、同理心、直觉、照顾他人",
    meaningRev: "情绪化、缺乏情感边界、依赖",
    keywords: ["同理", "智慧", "照顾", "直觉"],
  },
  {
    id: "cu14",
    name: "King of Cups",
    nameCn: "圣杯国王",
    type: "minor",
    suit: "cups",
    value: "14",
    imageFile: "MW_King_of_Cups.jpg",
    meaningUp: "情感成熟、同情心、平衡情感与理智",
    meaningRev: "情绪波动、操纵、酒精问题",
    keywords: ["成熟", "平衡", "同情", "智慧"],
  },

  // ===== 小阿尔卡纳 - 宝剑组 (Swords) =====
  {
    id: "sw01",
    name: "Ace of Swords",
    nameCn: "宝剑王牌",
    type: "minor",
    suit: "swords",
    value: "1",
    imageFile: "MW_Ace_of_Swords.jpg",
    meaningUp: "清晰思维、突破、新想法、真相揭露",
    meaningRev: "混乱思维、暴力、痛苦的真相",
    keywords: ["清晰", "突破", "真相", "思维"],
  },
  {
    id: "sw02",
    name: "Two of Swords",
    nameCn: "宝剑二",
    type: "minor",
    suit: "swords",
    value: "2",
    imageFile: "MW_Two_of_Swords.jpg",
    meaningUp: "难以选择、僵局、拒绝面对真相",
    meaningRev: "信息混乱、做出决定、打破僵局",
    keywords: ["僵局", "选择", "决定", "拒绝"],
  },
  {
    id: "sw03",
    name: "Three of Swords",
    nameCn: "宝剑三",
    type: "minor",
    suit: "swords",
    value: "3",
    imageFile: "MW_Three_of_Swords.jpg",
    meaningUp: "心碎、悲伤、分离、痛苦",
    meaningRev: "走出痛苦、原谅、疗愈",
    keywords: ["心碎", "悲伤", "分离", "疗愈"],
  },
  {
    id: "sw04",
    name: "Four of Swords",
    nameCn: "宝剑四",
    type: "minor",
    suit: "swords",
    value: "4",
    imageFile: "MW_Four_of_Swords.jpg",
    meaningUp: "休息恢复、冥想、退隐充电",
    meaningRev: "回避问题、强制活动、恢复中",
    keywords: ["休息", "恢复", "冥想", "充电"],
  },
  {
    id: "sw05",
    name: "Five of Swords",
    nameCn: "宝剑五",
    type: "minor",
    suit: "swords",
    value: "5",
    imageFile: "MW_Five_of_Swords.jpg",
    meaningUp: "冲突、败北、自私、不道德的胜利",
    meaningRev: "和解、后悔、想要和平",
    keywords: ["冲突", "败北", "自私", "和解"],
  },
  {
    id: "sw06",
    name: "Six of Swords",
    nameCn: "宝剑六",
    type: "minor",
    suit: "swords",
    value: "6",
    imageFile: "MW_Six_of_Swords.jpg",
    meaningUp: "过渡期、离开麻烦、转变、旅行",
    meaningRev: "抵制变化、拖延、未解决的问题",
    keywords: ["过渡", "离开", "转变", "旅行"],
  },
  {
    id: "sw07",
    name: "Seven of Swords",
    nameCn: "宝剑七",
    type: "minor",
    suit: "swords",
    value: "7",
    imageFile: "MW_Seven_of_Swords.jpg",
    meaningUp: "欺骗、狡猾、独自行动、逃避",
    meaningRev: "被揭穿、来清算、改变策略",
    keywords: ["欺骗", "狡猾", "逃避", "策略"],
  },
  {
    id: "sw08",
    name: "Eight of Swords",
    nameCn: "宝剑八",
    type: "minor",
    suit: "swords",
    value: "8",
    imageFile: "MW_Eight_of_Swords.jpg",
    meaningUp: "自我设限、受困感、无力感、思维桎梏",
    meaningRev: "解脱自我设限、看清真相、找到出路",
    keywords: ["受困", "无力", "设限", "解脱"],
  },
  {
    id: "sw09",
    name: "Nine of Swords",
    nameCn: "宝剑九",
    type: "minor",
    suit: "swords",
    value: "9",
    imageFile: "MW_Nine_of_Swords.jpg",
    meaningUp: "焦虑、噩梦、担忧过度、心理压力",
    meaningRev: "走出黑暗、寻求帮助、内心和平",
    keywords: ["焦虑", "噩梦", "担忧", "压力"],
  },
  {
    id: "sw10",
    name: "Ten of Swords",
    nameCn: "宝剑十",
    type: "minor",
    suit: "swords",
    value: "10",
    imageFile: "MW_Ten_of_Swords.jpg",
    meaningUp: "结束、背叛、痛苦的教训、触底反弹",
    meaningRev: "从低谷恢复、抵制结局、缓慢复苏",
    keywords: ["结束", "背叛", "教训", "复苏"],
  },
  {
    id: "sw11",
    name: "Page of Swords",
    nameCn: "宝剑侍从",
    type: "minor",
    suit: "swords",
    value: "11",
    imageFile: "MW_Page_of_Swords.jpg",
    meaningUp: "好奇心、思维敏锐、坦率、新想法",
    meaningRev: "八卦、鲁莽、缺乏计划",
    keywords: ["好奇", "敏锐", "坦率", "想法"],
  },
  {
    id: "sw12",
    name: "Knight of Swords",
    nameCn: "宝剑骑士",
    type: "minor",
    suit: "swords",
    value: "12",
    imageFile: "MW_Knight_of_Swords.jpg",
    meaningUp: "果断行动、雄心勃勃、思维快速、直接",
    meaningRev: "冲动鲁莽、暴躁、缺乏方向",
    keywords: ["果断", "雄心", "快速", "直接"],
  },
  {
    id: "sw13",
    name: "Queen of Swords",
    nameCn: "宝剑皇后",
    type: "minor",
    suit: "swords",
    value: "13",
    imageFile: "MW_Queen_of_Swords.jpg",
    meaningUp: "独立、清晰思维、直言不讳、设立边界",
    meaningRev: "冷酷无情、苦涩、过于批判",
    keywords: ["独立", "清晰", "直接", "边界"],
  },
  {
    id: "sw14",
    name: "King of Swords",
    nameCn: "宝剑国王",
    type: "minor",
    suit: "swords",
    value: "14",
    imageFile: "MW_King_of_Swords.jpg",
    meaningUp: "理智权威、公正决策、真理、智慧领导",
    meaningRev: "独裁、操纵、冷酷无情",
    keywords: ["理智", "公正", "权威", "智慧"],
  },

  // ===== 小阿尔卡纳 - 五角星组 (Pentacles) =====
  {
    id: "pe01",
    name: "Ace of Pentacles",
    nameCn: "五角星王牌",
    type: "minor",
    suit: "pentacles",
    value: "1",
    imageFile: "MW_Ace_of_Pentacles.jpg",
    meaningUp: "物质新开始、财富机遇、事业起步、繁荣",
    meaningRev: "失去财富机会、贪婪、物质不安全",
    keywords: ["财富", "机遇", "起步", "繁荣"],
  },
  {
    id: "pe02",
    name: "Two of Pentacles",
    nameCn: "五角星二",
    type: "minor",
    suit: "pentacles",
    value: "2",
    imageFile: "MW_Two_of_Pentacles.jpg",
    meaningUp: "平衡多任务、适应变化、时间管理",
    meaningRev: "失衡、无法应对、杂乱无章",
    keywords: ["平衡", "多任务", "适应", "管理"],
  },
  {
    id: "pe03",
    name: "Three of Pentacles",
    nameCn: "五角星三",
    type: "minor",
    suit: "pentacles",
    value: "3",
    imageFile: "MW_Three_of_Pentacles.jpg",
    meaningUp: "团队合作、精通技艺、共同建造",
    meaningRev: "缺乏团队精神、工作质量低、不合作",
    keywords: ["团队", "技艺", "合作", "建造"],
  },
  {
    id: "pe04",
    name: "Four of Pentacles",
    nameCn: "五角星四",
    type: "minor",
    suit: "pentacles",
    value: "4",
    imageFile: "MW_Four_of_Pentacles.jpg",
    meaningUp: "保守财富、控制、稳定、吝啬",
    meaningRev: "放开掌控、慷慨、财务不稳定",
    keywords: ["保守", "控制", "稳定", "财富"],
  },
  {
    id: "pe05",
    name: "Five of Pentacles",
    nameCn: "五角星五",
    type: "minor",
    suit: "pentacles",
    value: "5",
    imageFile: "MW_Five_of_Pentacles.jpg",
    meaningUp: "财务困境、贫穷感、寻求帮助、孤立",
    meaningRev: "走出困境、接受帮助、财务改善",
    keywords: ["困境", "贫穷", "孤立", "求助"],
  },
  {
    id: "pe06",
    name: "Six of Pentacles",
    nameCn: "五角星六",
    type: "minor",
    suit: "pentacles",
    value: "6",
    imageFile: "MW_Six_of_Pentacles.jpg",
    meaningUp: "慷慨给予、接受帮助、平衡财富、公平",
    meaningRev: "不慷慨、债务、权力失衡",
    keywords: ["慷慨", "给予", "平衡", "帮助"],
  },
  {
    id: "pe07",
    name: "Seven of Pentacles",
    nameCn: "五角星七",
    type: "minor",
    suit: "pentacles",
    value: "7",
    imageFile: "MW_Seven_of_Pentacles.jpg",
    meaningUp: "耐心等待、长期投资、评估进展",
    meaningRev: "缺乏长远眼光、急功近利、投资回报低",
    keywords: ["耐心", "投资", "评估", "等待"],
  },
  {
    id: "pe08",
    name: "Eight of Pentacles",
    nameCn: "五角星八",
    type: "minor",
    suit: "pentacles",
    value: "8",
    imageFile: "MW_Eight_of_Pentacles.jpg",
    meaningUp: "勤奋工作、精通技艺、专注细节、学习",
    meaningRev: "完美主义、工作狂、缺乏技能",
    keywords: ["勤奋", "技艺", "专注", "学习"],
  },
  {
    id: "pe09",
    name: "Nine of Pentacles",
    nameCn: "五角星九",
    type: "minor",
    suit: "pentacles",
    value: "9",
    imageFile: "MW_Nine_of_Pentacles.jpg",
    meaningUp: "独立自给、物质享受、自我满足、丰盛",
    meaningRev: "物质依赖、过度消费、虚假成功",
    keywords: ["独立", "享受", "自给", "丰盛"],
  },
  {
    id: "pe10",
    name: "Ten of Pentacles",
    nameCn: "五角星十",
    type: "minor",
    suit: "pentacles",
    value: "10",
    imageFile: "MW_Ten_of_Pentacles.jpg",
    meaningUp: "长期财富、家族遗产、稳定繁荣、传承",
    meaningRev: "家族冲突、财富损失、不稳定",
    keywords: ["财富", "家族", "传承", "繁荣"],
  },
  {
    id: "pe11",
    name: "Page of Pentacles",
    nameCn: "五角星侍从",
    type: "minor",
    suit: "pentacles",
    value: "11",
    imageFile: "MW_Page_of_Pentacles.jpg",
    meaningUp: "学习实践、新机遇、踏实可靠、研究",
    meaningRev: "缺乏进取心、不务实、错过机会",
    keywords: ["学习", "实践", "踏实", "机遇"],
  },
  {
    id: "pe12",
    name: "Knight of Pentacles",
    nameCn: "五角星骑士",
    type: "minor",
    suit: "pentacles",
    value: "12",
    imageFile: "MW_Knight_of_Pentacles.jpg",
    meaningUp: "踏实可靠、努力工作、耐心坚持、方法论",
    meaningRev: "过于固执、乏味、停滞不前",
    keywords: ["踏实", "努力", "耐心", "可靠"],
  },
  {
    id: "pe13",
    name: "Queen of Pentacles",
    nameCn: "五角星皇后",
    type: "minor",
    suit: "pentacles",
    value: "13",
    imageFile: "MW_Queen_of_Pentacles.jpg",
    meaningUp: "实际关怀、物质安全、养育、智慧管理",
    meaningRev: "自私、过度工作、嫉妒",
    keywords: ["关怀", "安全", "养育", "管理"],
  },
  {
    id: "pe14",
    name: "King of Pentacles",
    nameCn: "五角星国王",
    type: "minor",
    suit: "pentacles",
    value: "14",
    imageFile: "MW_King_of_Pentacles.jpg",
    meaningUp: "财富成就、商业成功、踏实领导、慷慨",
    meaningRev: "固执、物质主义、腐败",
    keywords: ["财富", "成功", "踏实", "领导"],
  },
];

// 领域配置
export const DOMAINS = [
  { id: "love", name: "爱情", icon: "💕", color: "from-pink-600 to-rose-800" },
  { id: "career", name: "事业", icon: "⚡", color: "from-amber-600 to-yellow-800" },
  { id: "wealth", name: "财富", icon: "💎", color: "from-emerald-600 to-green-800" },
  { id: "general", name: "综合", icon: "🌙", color: "from-violet-600 to-purple-800" },
];

// 牌阵配置
export const SPREADS = [
  {
    id: "single",
    name: "每日一牌",
    description: "获取今日指引与运势",
    cardCount: 1,
    icon: "✨",
    positions: ["今日指引"],
    isFree: true,
  },
  {
    id: "three",
    name: "过去·现在·未来",
    description: "深度解析你的问题脉络",
    cardCount: 3,
    icon: "🌟",
    positions: ["过去", "现在", "未来"],
    isFree: true,
  },
];

// 随机抽取卡牌（含正逆位）
export function drawCards(count: number): Array<{ card: TarotCard; reversed: boolean }> {
  const shuffled = [...TAROT_CARDS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map((card) => ({
    card,
    reversed: Math.random() < 0.3, // 30% 概率逆位
  }));
}
